# Generated by Django 4.0.4 on 2022-04-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fWriters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postagens',
            new_name='Postagem',
        ),
    ]
